version: 0.0
os: linux

file_exists_behavior: OVERWRITE

files:
  - source: index.html
    destination: /var/www/html
  - source: ressources
    destination: /var/www/html/ressources

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
